### PR TITLE
Update for ManifoldsBase 0.15

### PR DESCRIPTION
**Pull request by mateuszbaran**
See https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/170

### CODE REVIEW

**Comment by mateuszbaran** [comment]
@kellertuer We can't get CI passing here without merging https://github.com/JuliaManifolds/Manifolds.jl/pull/642#issuecomment-1773874412 and tagging it, and we can't get CI passing there without merging and tagging this PR :disappointed: .

**Comment by kellertuer** [comment]
I do not follow why that is the case, how did we manage to get this deadlock?
We should maybe avoid having this then? Are we using both in their tests?

If both work for you locally we could merge and register both.

**Comment by mateuszbaran** [comment]
Manifolds.jl is a test dependency of ManifoldDiff.jl -- this is the issue. I will re-check tests here, I'm not sure if I tested it on the latest commit of 0.15.

**Comment by kellertuer** [comment]
or to be more precise, I was hoping, Manifolds.jl works without Diff.

**Comment by mateuszbaran** [comment]
ManifoldDiff.jl is a hard dependency of Manifolds.jl.

**Comment by mateuszbaran** [comment]
ManifoldDiff.jl works locally, so I will merge and tag it.

**Pull request merged**
