### PR TITLE
Replace AD package extensions with DifferentiationInterface

### LINKED ISSUE #49: Using DifferentiationInterface for AD
Hi @kellertuer @mateuszbaran,

Would you would like to try [DifferentiationInterface.jl](https://github.com/JuliaDiff/DifferentiationInterface.jl) to handle the various AD backends in a unified manner? This would allow you to get rid of the extensions, and probably simplify some code.
I'm happy to lend a hand.

Related:
- #29

### PR DESCRIPTION
**Pull request by gdalle**
Fixes #49. Here are the main changes:

- [x] Add dependency on ADTypes and DifferentiationInterface
- [x] Implement `_derivative`, `_gradient`, `_jacobian` and `_hessian` using DI
- [x] Remove package extensions for FiniteDiff, FiniteDifferences, ForwardDiff, ReverseDiff, Zygote 
- [x] Replace backend constructors with their ADTypes counterparts everywhere.
- [x] Remove package extensions from docs.
- [x] Figure out what to do about `AbstractDiffBackend`, since it is apparently used downstream. Replace it with `Union{ADTypes.AbstractADType, ExplicitEmbeddedBackend}`? Right now I removed annotations in this package, and set `AbstractDiffBackend = Any` for downstream uses.
- [x] Fix broken test. It seems that we try to compute a Jacobian for a function with a scalar output?
- [x] Bump version to v0.4.0.
- [x] Undo changes for testing with next Manifolds version.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
Thanks for working on this update :+1: 

> * Figure out what to do about `AbstractDiffBackend`, since it is apparently used downstream. Replace it with `Union{ADTypes.AbstractADType, ExplicitEmbeddedBackend}`? Right now I removed annotations in this package, and set `AbstractDiffBackend = Any` for downstream uses.

Since this is a breaking change, I think we can just remove `AbstractDiffBackend` entirely and switch to `ADTypes.AbstractADType` in downstream packages.

> *  Fix broken test. It seems that we try to compute a Jacobian for a function with a scalar output?

It's technically valid but I don't think it's a feature we rely on anywhere. I think we can switch the test to use a vector-valued function.

**Comment by gdalle** [comment]
> Since this is a breaking change, I think we can just remove AbstractDiffBackend entirely and switch to ADTypes.AbstractADType in downstream packages.

I agree, but this would prevent us from testing here because the test dependencies contain a version of Manifolds.jl which still requires `AbstractDiffBackend`.

**Comment by mateuszbaran** [comment]
Right, in this case making `AbstractDiffBackend` an alias for `Any` is useful.

**Comment by gdalle** [comment]
The fact that we use Manifolds in testing also means we cannot bump ManifoldsDiff to v0.4.0 in the current state, because it is not permitted by the Manifolds compat bound. The right way would be testing with a `dev` version of Manifolds where the compat v0.4.0 has been added for ManifoldsDiff. That would also make the `AbstractDiffBackend = Any` hotfix superfluous.

**Comment by mateuszbaran** [comment]
That's what I sometimes do locally when making breaking changes but I don't know about any way to do it on CI.

**Comment by gdalle** [comment]
The last commit gives you an example of how to do that, using my [custom branch](https://github.com/gdalle/Manifolds.jl/tree/gd/manifoldsdiff_update) of Manifolds where the compat entry has been upgraded and the `AbstractDiffBackend` import has been removed.

**Comment by mateuszbaran** [comment]
Nice, I didn't know that trick.

**Comment by kellertuer** [comment]
This indeed looks like a very neat trick! Thanks for illustrating that here.

**Comment by gdalle** [comment]
All the tests are passing with my custom branch of the downstream Manifolds (except codecov). I will now remove my Pkg tricks, the tests will thus fail but it will still be good to merge.

**Comment by gdalle** [comment]
@kellertuer this is good to go

**Review by mateuszbaran — APPROVED** [review]
LGTM.

By the way, is https://github.com/JuliaManifolds/Manifolds.jl/pull/772 good to go also?

**Comment by gdalle** [comment]
Yeah you can ship that one too

**Pull request merged**
